
% create a GUI for epoching data from the exported compumedics files

function EpochProbeDataGUI(varargin)

clc
clear
close all

RawData = [];           % this is the data that will be loaded from the data file
NChannels = [];
NSamples = [];
t = [];

FS = 8;
ControlColor = 'white';

% this is the full GUI figure
DataEpocher_fig = figure('Name','Probe Epoch',...
    'NumberTitle','off',...
    'units','normalized',...
    'Position',[0 .035 1 .9],...
    'toolbar','figure',...
    'menubar','none',...
    'color',ControlColor);

Top = 0.9;
LeftControls = 0.91;
RightControls = 0.001;
WidthControl = 0.08;
HeightControl = 0.025;      % starting top

Bottom = 0.02;
Height = 1-Bottom;
Ax = axes('parent',DataEpocher_fig,...
        'units', 'normalized',...
        'position', [0.081 Bottom 0.82 Height]);

Top = Top-HeightControl;
uicontrol('style','pushbutton', ...
    'units', 'normalized', ...
    'position', [LeftControls Top WidthControl HeightControl], ...
    'HorizontalAlignment','center', ...
    'parent', DataEpocher_fig, ...
    'string', 'find *.dat file',...
    'callback',@GetDataFile);    
    
% set/get the file where the *.dat file is
Top = Top-HeightControl;
dat_pathname = '/Users/dean/Documents/PhD/Probe Analysis/Compumedics Data/UBET_Probe_DAT';
dat_filename = '*.dat filename';        % declare this here to make it a global
dat_FileAndPath = [dat_pathname '/' dat_filename];
TextBox_filename = uicontrol('style','text', ...
    'units', 'normalized', ...
    'position', [LeftControls Top WidthControl HeightControl], ...
    'HorizontalAlignment','center', ...
    'parent', DataEpocher_fig, ...
    'string', dat_filename,...
    'backgroundcolor',ControlColor);

% this should be a mat file in the same folder
Top = Top-2*HeightControl;
uicontrol('style','pushbutton', ...
    'units', 'normalized', ...
    'position', [LeftControls Top WidthControl HeightControl], ...
    'HorizontalAlignment','center', ...
    'parent', DataEpocher_fig, ...
    'string', 'find *.mat file',...
    'callback',@GetMatFile);    
    
% set/get the file where the *.dat file is
Top = Top-HeightControl;
mat_pathname = '/Users/dean/Documents/PhD/Probe Analysis/Compumedics Data/UBET_Probe_DAT';
mat_filename = '*.mat filename';        % declare this here to make it a global
mat_DataFileAndPath = [mat_pathname '/' mat_filename];
TextBox_filename = uicontrol('style','text', ...
    'units', 'normalized', ...
    'position', [LeftControls Top WidthControl HeightControl], ...
    'HorizontalAlignment','center', ...
    'parent', DataEpocher_fig, ...
    'string', mat_filename,...
    'backgroundcolor',ControlColor);

Top = Top-2*HeightControl;
uicontrol('style','pushbutton', ...
    'units', 'normalized', ...
    'position', [LeftControls Top WidthControl HeightControl], ...
    'HorizontalAlignment','center', ...
    'parent', DataEpocher_fig, ...
    'string', 'load data',...
    'callback',@LoadData); 

% view data to identify bad channels, need to be able to scroll through it
% this will be a file that is about 1GB in size
% view it in 10 second blocks
Top = Top-2*HeightControl;
uicontrol('style','pushbutton', ...
    'units', 'normalized', ...
    'position', [LeftControls Top WidthControl HeightControl], ...
    'HorizontalAlignment','center', ...
    'parent', DataEpocher_fig, ...
    'string', 'plot data',...
    'callback',@PlotData);   

% use a back-ground high-lighter to show where stims occur

% use a tick box to identify bad channels

    function GetDataFile(varargin)
        [dat_filename dat_pathname] = uigetfile(dat_pathname,'*.dat');
        dat_FileAndPath = [dat_pathname '/' dat_filename];
        set(TextBox_filename,'string',dat_filename)
    end

    function GetMatFile(varargin)
        [mat_filename mat_pathname] = uigetfile(dat_pathname,'*.mat');
        mat_FileAndPath = [mat_pathname '/' mat_filename];
        set(TextBox_filename,'string',mat_filename)
    end

    function LoadData(varargin)
        RawData = load(dat_FileAndPath);
        NChannels = size(RawData,2);
        NSamples = size(RawData,1);
        t = RawData(:,1);
    end

    function PlotData(varargin)
        plot(t,RawData(:,2),'parent',Ax)
    end
end